%\VignetteKeywords{Database}
%\VignetteDepends{prostateCancerGrasso}
%\VignettePackage{prostateCancerGrasso}
%\VignetteIndexEntry{prostateCancerGrasso}
\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}
In this document, I describe how the GEO data entry for the Varambally data was processed and saved into an object for analysis in Bioconductor. First of all load the relevant libraries for grabbing and manipulaing the data

<<eval=FALSE>>=
library(GEOquery)
library(dplyr)
library(tidyr)
@


Now use the `getGEO` function with the correct ID

<<eval=FALSE>>=
geoData <- getGEO("GSE3325")[[1]]
geoData
@

The phenoData contains lots of metadata from GEO that probably won't be useful for our analysis

<<eval=FALSE>>=
pData(geoData) <- pData(geoData)[,c("geo_accession","title","description")]
Sample_Group <- NULL

Sample_Group[grep("Benign", pData(geoData)$title)] <- "Benign"

Sample_Group[grep("prostate cancer",pData(geoData)$title)] <- "PC"

Sample_Group[grep("Metastatic", pData(geoData)$title)] <- "Metastatic"
pData(geoData)$Sample_Group <- Sample_Group
colnames(fData(geoData))[which(colnames(fData(geoData)) == "Gene Symbol")] <- "Symbol"
varambally <- geoData
save(varambally, file="data/varambally.rda",compress="xz")
@


\end{document}